# Generated by Django 2.1.5 on 2019-02-18 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0002_teachpost_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachpost',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 15, 48, 43, 600006)),
        ),
    ]
