# Generated by Django 2.1.5 on 2019-02-18 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_agriculturepost_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturepost',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 15, 44, 29, 262952)),
        ),
    ]
