# Generated by Django 2.1.5 on 2019-02-18 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20190218_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspost',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 16, 41, 30, 638844)),
        ),
    ]
