# Generated by Django 2.1.5 on 2019-02-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturepost',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
